name: 🚀 Feature Request
description: Suggest an idea for Calendar Card Pro
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: checkboxes
    attributes:
      label: Requirements
      options:
        - label: I've checked that I'm using the latest version of Calendar Card Pro
          required: true
        - label: I've verified this feature isn't already available in the configuration options
          required: true
        - label: I've searched existing issues to verify this hasn't already been requested
          required: true
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: >
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: >
        A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: >
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Example use case
      description: >
        Describe how you would use this feature in your setup.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: >
        Add any other context, mockups, or screenshots about the feature request.
    validations:
      required: false
  - type: markdown
    attributes:
      value: >
        Thanks for contributing to Calendar Card Pro! 🎉
