#!/usr/bin/env node
/**
 * Generate per-language starting files for editor translation work.
 *
 * This is an authoring tool, not a CI gate, and it needs the Home Assistant frontend
 * wheel described in `l10n-oracle.mjs`.
 *
 *   HA_FRONTEND_TRANSLATIONS=/tmp/hafe/x/hass_frontend/static/translations \
 *     node scripts/l10n-handoff.mjs
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { GLOSSARY_TERMS, NOUN_CAPS_LANGUAGES } from './editor-glossary.mjs';
import { loadHaLanguage, LANGS } from './l10n-oracle.mjs';
import { loadEditorModule } from './load-editor-schema.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'l10n-handoff');

/** Loose match: case, surrounding whitespace, quote style and trailing stops ignored. */
const normalise = (s) =>
  String(s)
    .trim()
    .toLowerCase()
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201c\u201d]/g, '"')
    .replace(/[.:!?\u2026]+$/, '');

const { EDITOR_STRINGS } = await loadEditorModule(ROOT);

const haEn = loadHaLanguage('en');
// Self-test before believing any absence.
if (!Object.values(haEn).includes('Calendar')) {
  console.error('\n  FATAL: self-test failed — "Calendar" is not in the English corpus.\n');
  process.exit(2);
}

// English text -> HA key.
const byEnglish = new Map();
for (const [key, value] of Object.entries(haEn)) {
  if (typeof value !== 'string') continue;
  const n = normalise(value);
  if (!byEnglish.has(n)) byEnglish.set(n, key);
}

// The termbase, sliced per language.
const termsByLang = Object.fromEntries(LANGS.map((l) => [l, []]));
const decidedByTerm = new Map(); // term -> { lang -> form }
const rejectedByLang = Object.fromEntries(LANGS.map((l) => [l, []]));
for (const term of GLOSSARY_TERMS) {
  decidedByTerm.set(term.name, term.decided);
  for (const lang of LANGS) {
    if (!termsByLang[lang]) continue;
    termsByLang[lang].push({
      term: term.name,
      sense: term.sense,
      value: term.decided[lang] ?? '—',
    });
    for (const form of term.rejected[lang] ?? []) rejectedByLang[lang].push(form);
  }
}

const totals = [];
for (const lang of LANGS) {
  const ha = loadHaLanguage(lang);
  const mine = JSON.parse(
    readFileSync(join(ROOT, `src/rendering/editor/translations/${lang}.json`), 'utf8'),
  );

  const missing = Object.keys(EDITOR_STRINGS).filter((k) => mine[k] === undefined);
  const fills = [];
  const dropped = [];
  for (const key of missing) {
    const english = EDITOR_STRINGS[key];
    const haKey = byEnglish.get(normalise(english));
    if (!haKey) continue;
    let value = ha[haKey];
    let source = haKey;
    if (value === undefined) continue;
    // Ignore untranslated HA values.
    if (value === haEn[haKey]) continue;

    // The glossary is a decision; Home Assistant is evidence.
    const decided = decidedByTerm.get(normalise(english))?.[lang];
    if (decided && decided !== value) {
      value = decided;
      source = 'glossary';
    }

    // Do not propose glossary-rejected forms.
    if (rejectedByLang[lang].some((form) => value.includes(form))) {
      dropped.push({ key, english, value, why: 'contradicts a rejected term' });
      continue;
    }

    // Drop unit suffixes and inflected fragments that are not standalone labels.
    if (value.length <= 2 || (/\.$/.test(value) && !/\.$/.test(english))) {
      dropped.push({ key, english, value, why: 'looks like an abbreviation or a fragment' });
      continue;
    }

    fills.push({ key, english, value, haKey: source });
  }

  const helpers = missing.filter((k) => k.endsWith('.helper'));
  const undecided = termsByLang[lang].filter((t) => t.value === '—' || /^\*.*\*$/.test(t.value));

  const lines = [];
  lines.push(`# Stage 1 Handoff — \`${lang}\``);
  lines.push('');
  lines.push(
    `Generated by \`scripts/l10n-handoff.mjs\`. A snapshot, not a live artefact: the ` +
      `termbase that governs this work is \`scripts/editor-glossary.mjs\`, ` +
      `and that is the file to edit if a decision here turns out wrong.`,
  );
  lines.push('');
  lines.push('## Scope');
  lines.push('');
  lines.push(
    `- **${Object.keys(mine).length} of ${Object.keys(EDITOR_STRINGS).length}** strings present.`,
  );
  lines.push(
    `- **${missing.length} missing**, of which **${helpers.length} are prose** (\`.helper\`).`,
  );
  lines.push(
    `- The prose is the harder half and is deliberately **last**: by the time you reach it ` +
      `you will have decided every term it refers to.`,
  );
  lines.push(
    `- Work the panel chrome and first-screen labels **first**. A language at 40% coverage ` +
      `looks entirely untranslated if the panel titles are English, and entirely translated ` +
      `if they are not.`,
  );
  lines.push('');
  lines.push('## Mined Strings — Paste These First');
  lines.push('');
  if (fills.length === 0) {
    lines.push(
      "Home Assistant's table fills nothing here that is not already present. That is the " +
        'normal result — the mine yields ~1.5% across all nine languages.',
    );
  } else {
    lines.push(
      `${fills.length} string${fills.length === 1 ? '' : 's'} taken from Home Assistant's own ` +
        `frontend, matched on **English text** and rejected where HA's value was itself ` +
        `untranslated. Check each one reads correctly in context before keeping it.`,
    );
    lines.push('');
    lines.push('```json');
    for (const f of fills) lines.push(`  ${JSON.stringify(f.key)}: ${JSON.stringify(f.value)},`);
    lines.push('```');
    lines.push('');
    lines.push('| key | English | proposed | HA source key |');
    lines.push('|---|---|---|---|');
    for (const f of fills) {
      lines.push(`| \`${f.key}\` | ${f.english} | **${f.value}** | \`${f.haKey}\` |`);
    }
  }
  if (dropped.length > 0) {
    lines.push('');
    lines.push('### Rejected By The Miner');
    lines.push('');
    lines.push(
      'Home Assistant had a value for these and it was thrown away. Listed so the ' +
        'omission is visible rather than silent — if one looks salvageable, it still ' +
        'needs writing by hand.',
    );
    lines.push('');
    lines.push('| key | English | HA offered | why rejected |');
    lines.push('|---|---|---|---|');
    for (const d of dropped) {
      lines.push(`| \`${d.key}\` | ${d.english} | ${d.value} | ${d.why} |`);
    }
  }
  lines.push('');
  lines.push('## Your Terms');
  lines.push('');
  lines.push('Decided once, for all nine languages. Use these; do not re-decide them.');
  lines.push('');
  lines.push('| term | sense | use |');
  lines.push('|---|---|---|');
  for (const t of termsByLang[lang]) {
    lines.push(
      `| ${t.term} | ${t.sense} | ${t.value === '—' ? '**you decide**' : `**${t.value}**`} |`,
    );
  }
  lines.push('');
  if (undecided.length > 0) {
    lines.push('### Undecided — You Own These');
    lines.push('');
    lines.push(
      'Nothing external arbitrates them: Home Assistant has no term, the card has no ' +
        'string, and no other language can supply one. Decide each, then **write it back ' +
        'into the glossary** so the next session finds it decided.',
    );
    lines.push('');
    for (const t of undecided) lines.push(`- **${t.term}** — ${t.sense}`);
    lines.push('');
  }
  lines.push('## Before You Start');
  lines.push('');
  lines.push(
    `1. This language ${NOUN_CAPS_LANGUAGES.includes(lang) ? 'capitalises nouns, so a multi-word label keeps its noun capitals' : 'does not capitalise nouns, so multi-word labels are sentence case'}. ` +
      'It is one decision, not 201.',
  );
  lines.push(
    '2. Fix the pre-existing strings first. `node scripts/check-i18n.mjs` lists every ' +
      'defect it can see in this file by name.',
  );
  lines.push(
    '3. Placeholders (`{count}`, `{width}`), the em dash `—` and `≥` must survive ' +
      'verbatim; the checks fail the build if they do not. Quotation marks should become ' +
      "this language's own, not stay English.",
  );
  lines.push(
    '4. Do not add an entry that is byte-identical to the English. If a word genuinely ' +
      'is the same, say so in `IDENTICAL_TO_ENGLISH_OK` in `scripts/check-i18n.mjs` ' +
      'rather than leaving it ambiguous.',
  );
  lines.push('');

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(join(OUT_DIR, `editor-l10n-${lang}.md`), `${lines.join('\n')}\n`, 'utf-8');
  totals.push({
    lang,
    missing: missing.length,
    helpers: helpers.length,
    fills: fills.length,
    dropped: dropped.length,
    undecided: undecided.length,
  });
}

console.log('lang  missing  prose  mined  dropped  undecided-terms');
for (const t of totals) {
  console.log(
    `${t.lang.padEnd(5)} ${String(t.missing).padStart(7)} ${String(t.helpers).padStart(6)} ` +
      `${String(t.fills).padStart(6)} ${String(t.dropped).padStart(8)} ${String(t.undecided).padStart(16)}`,
  );
}
console.log(`\ntotal mined across nine languages: ${totals.reduce((n, t) => n + t.fills, 0)}`);
